


/**
 * COPYRIGHT
 * ---------------------------------------------------------------------------------------------------------------------
 * Copyright (c) iSOFT INFRASTRUCTURE SOFTWARE CO., LTD. This software is proprietary to
 * iSOFT INFRASTRUCTURE SOFTWARE CO., LTD., and all rights are reserved by iSOFT INFRASTRUCTURE SOFTWARE CO., LTD.
 * Without the express written permission of the company, no organization or individual may copy, install, trial,
 * distribute, or reverse engineer this software. For terms of use and further details, please refer to the End User
 * License Agreement (EULA) or contact us business@i-soft.com.cn for more assistance.
 *
 * This file contains code from iSoft, which is licensed under the LGPL-2.1. However, due to a special exception,
 * you are not required to comply with the provisions of section 6a of LGPL-2.1. Specifically, you may distribute
 * your software, including this file, under terms of your choice, including proprietary licenses, without needing to
 * provide the source code or object code as specified in section 6a. For more details, please refer to the project's
 * LICENSE and EXCEPTION files and the specific exception statement.
 * ---------------------------------------------------------------------------------------------------------------------
 * FILE DESCRIPTION
 * ---------------------------------------------------------------------------------------------------------------------
 * @MCU         : S32K148
 * @file        : BswM_Lcfg_BswMConfig.c
 * @licence     : 
 * @date        : 2026-09-09 23:13:43
 * @customer    : iSoft
 * @description : Link-Time Configuration parameter of BswM
 * @generator   : AUTOSAR classic Platform R23-11
 * @toolVersion : for_EasyXMen_V25.10_patch
 **********************************************************************************************************************/

/* =================================================== inclusions =================================================== */
#include "BswM_Lcfg.h" /* PRQA S 0380 */ /* VL_BswM_0380 */


/* PRQA S 3415, 6070 EOF */ /* VL_BswM_3415, VL_MTR_BswM_STCAL */
/* ===================================================== macros ===================================================== */
/* PRQA S 0380 ++ */ /* VL_BswM_0380 */
#define BSWM_EVRQST_COMMINITRESET_LCFG_Core0_Par0_NUM 1u


#define BSWM_ECUMSTATE0RULE_Core0_Par0_NUM 1u
#define BSWM_ECUMSTATE_LCFG_Core0_Par0_NUM 1u


#define BSWM_EVRQST_GENE0RULE_Core0_Par0_NUM 1u
#define BSWM_EVRQST_GENE_LCFG_Core0_Par0_NUM 1u
#define BSWM_EVRQST_GENE_REF_Core0_Par0_NUM 1u


#define BSWM_RULE_CONFIG_Core0_Par0_NUM 2u

#define BSWM_ACTION_LIST_LCFG_Core0_Par0_NUM 2u

#define BSWM_RULE_BswMRule_0_Core0_Par0_INDEX 0u
#define BSWM_RULE_BswMRule_1_Core0_Par0_INDEX 1u


#define BSWM_ACTION_ECUM_DRIVEWR_INIT_0_Core0_Par0 0u    /* BswMAction_0 */

/* PRQA S 0380 -- */
/* ================================================ type definitions ================================================ */

/* ========================================== internal function declarations ======================================== */

/* 0 : BswMRule_0 */
BSWM_LOCAL BswM_ActionListHandlerType BswM_Rule0Expression_Core0_Par0(void);
/* 1 : BswMRule_1 */
BSWM_LOCAL BswM_ActionListHandlerType BswM_Rule1Expression_Core0_Par0(void);

BSWM_LOCAL Std_ReturnType BswM_ActionList0_Core0_Par0(void);    /* BswMActionList_0 */
BSWM_LOCAL Std_ReturnType BswM_ActionList1_Core0_Par0(void);    /* BswMActionList_1 */
/* ============================================ internal data definitions =========================================== */
/* Conditional expressions are generated by configuration and may violate the*/
/* BswMConfig*/
/********BswMEventRequestPort**********/
#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_RqstPortLcCfgType BswM_EvRqst_ComMInitReset_LCfg_Core0_Par0[BSWM_EVRQST_COMMINITRESET_LCFG_Core0_Par0_NUM] = {
    /* BswMEventRequestPort_0 : BswMComMInitiateReset */
    {
        NULL_PTR,     /*belongToRlue*/
        0u,          /*belongToRlueNum*/
        BSWM_IMMEDIATE, /*BswMEventRequestProcessing*/
    },
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_EventRqstPortLCfgType BswM_EvRqstLCfg_Core0_Par0 = {
    &(BswM_EvRqst_ComMInitReset_LCfg_Core0_Par0[0u]), /*BswMComMInitiateReset*/
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

/*********************BswMModeRequestPort******************/
#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswMRulePbIndexType BswM_EcuMState0Rule_Core0_Par0[BSWM_ECUMSTATE0RULE_Core0_Par0_NUM] = {
    {
        0u,  /* BswMRule_0 */
    },
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_RqstPortLcCfgType BswM_EcuMState_LCfg_Core0_Par0[BSWM_ECUMSTATE_LCFG_Core0_Par0_NUM] = {
    /* BswMModeRequestPort_0 : BswMEcuMIndication */
    {
        &BswM_EcuMState0Rule_Core0_Par0[0u],
        1u,          /*belongToRlueNum*/
        BSWM_IMMEDIATE, /*BswMEventRequestProcessing*/
    },
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswMRulePbIndexType BswM_GeneRqst0Rule_Core0_Par0[BSWM_EVRQST_GENE0RULE_Core0_Par0_NUM] = {
    {
        1u,  /* BswMRule_1 */
    },
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_RqstPortLcCfgType BswM_GeneRqst_LCfg_Core0_Par0[BSWM_EVRQST_GENE_LCFG_Core0_Par0_NUM] = {
    /* BswMModeRequestPort_1 : BswMGenericRequest */
    {
        &BswM_GeneRqst0Rule_Core0_Par0[0u],
        1u,          /*belongToRlueNum*/
        BSWM_IMMEDIATE, /*BswMEventRequestProcessing*/
    },
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_UserType BswM_GeneRqstUserRef_Core0_Par0[BSWM_EVRQST_GENE_REF_Core0_Par0_NUM] = {
    0u,   /* BswMModeRequestPort_1 : BswMGenericRequest */
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_ModeRqstPortLCfgType BswM_ModeRqstLCfg_Core0_Par0 = {
    &(BswM_EcuMState_LCfg_Core0_Par0[0u]),
    &(BswM_GeneRqst_LCfg_Core0_Par0[0u]),         /*BswMGenericRequest*/
    &(BswM_GeneRqstUserRef_Core0_Par0[0u]),        /*BswMModeRequesterId*/
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"


/*********Rules**********/
#define BSWM_START_SEC_VAR_CLEARED_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL BswM_RuleRunTimeType BswM_RuleRunTime_Core0_Par0[BSWM_RULE_CONFIG_Core0_Par0_NUM];
#define BSWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"
/* 0 : BswMRule_0 */
BSWM_LOCAL BswM_ActionListHandlerType BswM_Rule0Expression_Core0_Par0(void)
{
    BswM_ActionListHandlerType retVal = BSWM_MAX_ACTIONLIST_NUM;
    /* PRQA S 3120 ++ */ /* VL_QAC_MagicNum */
    if (ECUM_STATE_STARTUP == BswM_GetEcuMState())
    /* PRQA S 3120 -- */
    {
        {
            retVal = BSWM_AL_Core0_Par0_BswMActionList_0;
        }
        BswM_RuleRunTime_Core0_Par0[BSWM_RULE_BswMRule_0_Core0_Par0_INDEX].ruleStatus = BSWM_TRUE;
    }
    else
    {
        /* No ActionList */
        BswM_RuleRunTime_Core0_Par0[BSWM_RULE_BswMRule_0_Core0_Par0_INDEX].ruleStatus = BSWM_FALSE;
    }

    return retVal;
}
/* 1 : BswMRule_1 */
BSWM_LOCAL BswM_ActionListHandlerType BswM_Rule1Expression_Core0_Par0(void)
{
    BswM_ActionListHandlerType retVal = BSWM_MAX_ACTIONLIST_NUM;
    /* PRQA S 3120 ++ */ /* VL_QAC_MagicNum */
    if (1u == BswM_GetGeneRqstStatus(0u))
    /* PRQA S 3120 -- */
    {
        {
            retVal = BSWM_AL_Core0_Par0_BswMActionList_1;
        }
        BswM_RuleRunTime_Core0_Par0[BSWM_RULE_BswMRule_1_Core0_Par0_INDEX].ruleStatus = BSWM_TRUE;
    }
    else
    {
        /* No ActionList */
        BswM_RuleRunTime_Core0_Par0[BSWM_RULE_BswMRule_1_Core0_Par0_INDEX].ruleStatus = BSWM_FALSE;
    }

    return retVal;
}
#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_RuleLcCfgType BswM_RuleLCfg_Core0_Par0[BSWM_RULE_CONFIG_Core0_Par0_NUM] = {
    /* 0 : BswMRule_0 */
    {
        BswM_Rule0Expression_Core0_Par0, /* BswMLogicalExpression_0*/
        BSWM_UNDEFINED,                       /*BswMRuleInitState*/
        FALSE,                 /*BswMNestedExecutionOnly*/
    },
    /* 1 : BswMRule_1 */
    {
        BswM_Rule1Expression_Core0_Par0, /* BswMLogicalExpression_1*/
        BSWM_UNDEFINED,                       /*BswMRuleInitState*/
        FALSE,                 /*BswMNestedExecutionOnly*/
    },
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

/* actionList  */
#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
BSWM_LOCAL const BswM_ActionListLcCfgType BswM_actionLictLCfg_Core0_Par0[BSWM_ACTION_LIST_LCFG_Core0_Par0_NUM] = {
    /* index             actionListFunc */
    {/*  0 */ BswM_ActionList0_Core0_Par0}, /* BswMActionList_0 : -1 */
    {/*  1 */ BswM_ActionList1_Core0_Par0}, /* BswMActionList_1 : -1 */
};
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"


#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"
/* BswMActionList_0 */
BSWM_LOCAL Std_ReturnType BswM_ActionList0_Core0_Par0(void)
{
    Std_ReturnType ret = E_OK;

    do
    {
        /* PRQA S 2982, 3335, 3678, 4434, 3209, 3200   ++ */ /* VL_BswM_Action */
        /* 0 : BswMActionListItem_0 : BswMAction_0*/
        {
            /* 0 : BswMAction_0 : BswMEcuMDriverInitListBswM */
            EcuM_AL_DriverInitBswM(BSWM_ACTION_ECUM_DRIVEWR_INIT_0_Core0_Par0);
        }
        /* PRQA S 2982, 3335, 3678, 4434, 3209, 3200  -- */
    } while (0u); /* PRQA S 2743 */ /* VL_BswM_2743 */
    return ret;
}
#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"
#define BSWM_START_SEC_CODE
#include "BswM_MemMap.h"
/* BswMActionList_1 */
BSWM_LOCAL Std_ReturnType BswM_ActionList1_Core0_Par0(void)
{
    Std_ReturnType ret = E_OK;

    do
    {
        /* PRQA S 2982, 3335, 3678, 4434, 3209, 3200   ++ */ /* VL_BswM_Action */
        /* 0 : BswMActionListItem_0 : BswMAction_1*/
        {
            /* 1 : BswMAction_1 : BswMUserCallout */
            BswMUserCalloutFunc();
        }
        /* PRQA S 2982, 3335, 3678, 4434, 3209, 3200  -- */
    } while (0u); /* PRQA S 2743 */ /* VL_BswM_2743 */
    return ret;
}
#define BSWM_STOP_SEC_CODE
#include "BswM_MemMap.h"

/* ============================================ external data definitions =========================================== */

#define BSWM_START_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"
/**
 * BswM_PartitionLCfg_Core0_Par0
 * This structure contains the configuration of the BswM partition.
 */
/* PRQA S 1533 ++ */ /* VL_QAC_OneFunRef */
const BswM_PartitionLCfgType BswM_PartitionLCfg_Core0_Par0 = {
    &BswM_EvRqstLCfg_Core0_Par0,        /*evRqstLCfg*/
    &BswM_ModeRqstLCfg_Core0_Par0,      /*modeRqstLCfg*/
    2u,                            /*numOfRules*/
    &(BswM_RuleLCfg_Core0_Par0[0u]),    /*ruleLCfg*/
    0u,                     /*numOfDefRules*/
    NULL_PTR, /*defRuleRefLCfg*/
    &(BswM_RuleRunTime_Core0_Par0[0u]), /*ruleRutTimeStatus*/
    &(BswM_actionLictLCfg_Core0_Par0[0u]),
    2u, /*numOfActionList*/
};
/* PRQA S 1533 -- */
#define BSWM_STOP_SEC_CONST_UNSPECIFIED
#include "BswM_MemMap.h"

/* ========================================== external function definitions ========================================= */



